version: "3"
services:
  banco:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "master"
    ports:
      - "5432:5432"
    volumes:
      - /home/ubuntu/postgres:/var/lib/postgresql/data


networks:
  - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
